
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  categories: /categories
  tags: /tags
  archives: /archives
  #search: /search
  about: /about
  #rss: /atom.xml

# Miscelaneous
favicon: /logo.png
avatar: /logo.png

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
# - //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/pure/1.0.0/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true
#footer
index_page: /
github: https://github.com/shuhaoc

# Show number of visitors to each article.
# You can visit https://leancloud.cn get AppID and AppKey.
leancloud_visitors:
  enable: true
  app_id: TTmRFEaTeIaPpvpREjwBW7Us-gzGzoHsz
  app_key: NGwl0ufyzGnytmSoJNbuS96J
  security: false
  betterPerformance: true

links:
  Dozer: https://www.dozer.cc/
  Roc wong: https://roc-wong.github.io/
  晋哥哥的私房钱: http://jingege.me/
  翔工作室: https://blog.atcumt.com/